-- 1. PROFILES Table (Extends Supabase Auth)
-- Stores additional user data like name, role, and NIDN/NIM
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  full_name text,
  role text check (role in ('admin', 'dosen', 'mahasiswa')), -- Roles: BAAK (admin), Lecturer, Student
  nip_nim text, -- NIDN or NIM
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- 2. COURSES Table (Mata Kuliah)
create table public.courses (
  id bigint generated by default as identity primary key,
  code text unique not null, -- Kode Matkul (e.g., USA-001)
  name text not null,
  sks_t integer default 0,
  sks_p integer default 0,
  sks_pr integer default 0,
  total_sks integer generated always as (sks_t + sks_p + sks_pr) stored,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.courses enable row level security;
create policy "Courses are viewable by everyone." on courses for select using (true);
create policy "Only Admins can insert/update courses." on courses for all using (
  exists ( select 1 from profiles where id = auth.uid() and role = 'admin' )
);

-- 3. SCHEDULES Table (Jadwal Perkuliahan)
create table public.schedules (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade not null,
  lecturer_id uuid references public.profiles(id), -- Link to Dosen's profile
  class_name text not null, -- e.g., IF-1A
  day text not null, -- SENIN, SELASA, etc.
  start_time time not null,
  end_time time not null,
  room text not null, -- e.g., L-01
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.schedules enable row level security;
create policy "Schedules are viewable by everyone." on schedules for select using (true);
create policy "Only Admins can manage schedules." on schedules for all using (
  exists ( select 1 from profiles where id = auth.uid() and role = 'admin' )
);

-- 4. ATTENDANCE_LOGS Table (Live Monitoring)
create table public.attendance_logs (
  id bigint generated by default as identity primary key,
  schedule_id bigint references public.schedules(id) on delete cascade not null,
  lecturer_id uuid references public.profiles(id),
  status text check (status in ('HADIR', 'TELAT', 'IZIN', 'ALPHA')) default 'ALPHA',
  check_in_time timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Realtime for Monitoring Dashboard
alter publication supabase_realtime add table attendance_logs;

alter table public.attendance_logs enable row level security;
create policy "Read access for everyone" on attendance_logs for select using (true);
create policy "Lecturers can log attendance" on attendance_logs for insert with check (auth.uid() = lecturer_id);
create policy "Admins can update attendance" on attendance_logs for update using (
    exists ( select 1 from profiles where id = auth.uid() and role = 'admin' )
);

-- 5. FUNCTION to handle new user signup automatically
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'role');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
